# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1907b333cafdf0e42500cc1c7fe4982b2babdbf6d5bb0aa154b9b3d32ed47a13cc79dd4c48aaf819fb00ec43766a693bd279ba77f65d85e40f2c20783334583

test:
  secret_key_base: c81bbeadddc20053d1271d1c2ee6e35d2dd8e2ed5e4b9a92a35b2de7330a39fc3a461b141dcda482be84cc5d53a4716cd5fcfbcbead6c5c6ff580ef4fadd5bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
